# Generated by Django 5.1.6 on 2025-02-16 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrolstations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrolstation',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='petrolstation',
            name='diesel_price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='petrolstation',
            name='e10_price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
